from enum import Enum, auto

# auto() assigns the constant with the enumerate value (0..len(TokenType))

class TokenType(Enum):
    # Single character tokens
    LEFT_PAREN = auto()
    RIGHT_PAREN = auto()
    LEFT_BRACE = auto()
    RIGHT_BRACE = auto()
    LEFT_BRACKET = auto()
    RIGHT_BRACKET = auto()
    COMMA = auto()
    DOT = auto()
    MOD = auto()
    MINUS = auto()
    NEWLINE = auto()
    PLUS = auto()
    SEMICOLON = auto()
    SLASH = auto()
    SPACE = auto()
    STAR = auto()
    TAB = auto()

    # One or two character tokens
    BANG = auto()
    BANG_EQUAL = auto()
    EQUAL = auto()
    EQUAL_EQUAL = auto()
    GREATER_THAN = auto()
    GREATER_EQUAL = auto()
    LESS_THAN = auto()
    LESS_EQUAL = auto()

    # Literals
    IDENTIFIER = auto()
    STRING = auto()
    NUMBER = auto()

    # Keywords
    ADD = auto()
    AND = auto()
    AS = auto()
    BECOMES = auto()
    BREAK = auto()
    CLASS = auto()
    COMMENT = auto()
    DEFINE = auto()
    ELSE = auto()
    END = auto()
    FALSE = auto()
    FOR = auto()
    GREATER = auto()
    IF = auto()
    IMPORT = auto()
    IN = auto()
    IS = auto()
    LAMBDA = auto()
    LEAVE = auto()
    LESS = auto()
    LOOP = auto()
    NULL = auto()
    OR = auto()
    OTHERWISE = auto()
    OUT = auto()
    PRINT = auto()
    RETURN = auto()
    SET = auto()
    SUPER = auto()
    TAKES = auto()
    THAN = auto()
    THEN = auto()
    THIS = auto()
    THROUGH = auto()
    TO = auto()
    TRUE = auto()
    VAR = auto()
    WHILE = auto()

    # End of file
    EOF = auto()
